### ISSUE TITLE
docker images

### ISSUE THREAD

**Issue by guoshan-yang** [kfkme/kfkdock-lnmp#1]
安装完成之后，kfkdock_mysql57和mysql，有什么区别嘛，php，nginx等镜像前都加了一个kfkdock前缀，这个前缀在哪改了？

**Comment by dan381006472** [comment]
kfkdock_mysql57 ：mysql 5.7版本  
前缀更改  改根目录名称（kfkdock）

**Comment by guoshan-yang** [comment]
kfkdock_mysql57和mysql，有什么区别嘛？

**Comment by guoshan-yang** [comment]
Building mongo
Step 1/1 : FROM mongo
ERROR: Service 'mongo' failed to build: Get https://registry-1.docker.io/v2/: Bad Request

老是报这个错

**Comment by dan381006472** [comment]
kfkdock_mysql57和mysql 没有区别，是一样的，kfkdock_mysql 就是mysql

**Comment by dan381006472** [comment]
报错 多试几遍，可能因为网络的问题报错
另外最好配置下[加速器](https://github.com/kfkme/kfkdock/blob/master/README_DEPEND.md#%E9%85%8D%E7%BD%AE-docker-%E5%8A%A0%E9%80%9F%E5%99%A8)
