### ISSUE TITLE
nignx 自定义端口8080

### ISSUE THREAD

**Issue by mingge2016** [kfkme/kfkdock-lnmp#2]
nginx自定义端口，
`
nginx:
      build: ./etc/nginx
      privileged: true
      ports:
        - "8080:80"
        - "8443:443"
      links:
        - "php71"
        - "php56"
      volumes:
        - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./vhost/:/etc/nginx/conf.d/
        - ../www/:/var/www/
        - ./logs/nginx/:/var/log/nginx/

`

配置vhost:
`
server {
    listen      80;
    server_name phalcon7.cc;
    root        /var/www/myPhalcon/public;
    index       index.php index.html index.htm;
    charset     utf-8;

    location / {
        try_files $uri $uri/ /index.php?_url=$uri&$args;
    }

    location ~ \.php {
        fastcgi_pass  php71:9000;
        fastcgi_index /index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
`

主机访问：
http://phalcon7.cc:8080/
报错：
No input file specified.

**Comment by dan381006472** [comment]
现在问题还存在吗？
