### ISSUE TITLE
sudo docker-compose build报错

### ISSUE THREAD

**Issue by zhourunliang** [kfkme/kfkdock-lnmp#3]
Mac环境
执行sudo docker-compose build报如下错误
/bin/sh: 1: gpg: not found
ERROR: Service 'php71' failed to build: The command '/bin/sh -c gpg --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5 	&& gpg -a --export 40976EAF437D05B5 | apt-key add - 	&& apt-get update 	&& apt-get -y upgrade' returned a non-zero code: 127

**Comment by dan381006472** [comment]
问题解决了，请更新下代码，重新 sudo docker-compose build
