### ISSUE TITLE
windows下docker toolbox 中 docker-compose up -d 报错

### ISSUE THREAD

**Issue by zhourunliang** [kfkme/kfkdock-lnmp#5]
λ docker-compose up -d
Starting kfkdock_postgres_1 ... done
Starting kfkdock_mysql56_1  ... done
Starting kfkdock_mysql57_1  ... done
Starting kfkdock_redis_1    ... done
Starting kfkdock_mongo_1    ... done
Starting kfkdock_node_1     ... done
Starting kfkdock_php71_1    ... done
Starting kfkdock_php56_1    ... done
Starting kfkdock_nginx_1    ... error

ERROR: for kfkdock_nginx_1  Cannot start service nginx: b'OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/d/docker/kfkdock/etc/nginx/nginx.conf\\\\\\" to rootfs \\\\\\"/mnt/sda1/var/lib/docker/overlay2/609122e7e86311dea389e5488fe1e9a53565458f85baea4b83f7d079daadbb2d/merged\\\\\\" at \\\\\\"/mnt/sda1/var/lib/docker/overlay2/609122e7e86311dea389e5488fe1e9a53565458f85baea4b83f7d079daadbb2d/merged/etc/nginx/nginx.conf\\\\\\" caused \\\\\\"not a directory\\\\\\"\\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type'

ERROR: for nginx  Cannot start service nginx: b'OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/d/docker/kfkdock/etc/nginx/nginx.conf\\\\\\" to rootfs \\\\\\"/mnt/sda1/var/lib/docker/overlay2/609122e7e86311dea389e5488fe1e9a53565458f85baea4b83f7d079daadbb2d/merged\\\\\\" at \\\\\\"/mnt/sda1/var/lib/docker/overlay2/609122e7e86311dea389e5488fe1e9a53565458f85baea4b83f7d079daadbb2d/merged/etc/nginx/nginx.conf\\\\\\" caused \\\\\\"not a directory\\\\\\"\\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type'
ERROR: Encountered errors while bringing up the project.

**Comment by dan381006472** [comment]
查看是不是端口被占用
